apiVersion: v1
kind: Service
metadata:
  name: gowebserver
spec:
  type: ClusterIP
  selector:
    app: gowebserver
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
